### ISSUE TITLE
Run tests in CI

### ISSUE THREAD

**Issue by Sean-Der** [sepfy/libpeer#106]
We have a `tests` folder, would be nice to run them on github actions

**Comment by Sean-Der** [comment]
@sepfy any reason most of the tests are disabled?

**Comment by sepfy** [comment]
The test directory contains simple test programs I developed during my own testing, but I haven't had time to integrate them into the GitHub Actions workflow yet (Including automated verification of whether the function's output is correct, and so on.), so I have temporarily disabled it.

**Comment by Sean-Der** [comment]
Ok I will work on adding tests then!

I also plan on enabling a bunch of clang sanitizers. Hopefully prevents some crashes in the future :)
