### ISSUE TITLE
libpeer sample with HTTP_CONFIG

### ISSUE THREAD

**Issue by cy-jayasankar** [sepfy/libpeer#113]
hi, I could get the sample from example/generic working with MQTT_CONFIG. I would like to try sample with HTTP_CONFIG, can you please provide WHIP details like WHIP_HOST, WHIP_PATH  and WHIP_PORT to be used for testing?

**Comment by sepfy** [comment]
Hi, I started working on wiki, you can refer it to test  this feature
https://github.com/sepfy/libpeer/wiki/WebRTC-Server
