### ISSUE TITLE
Add clang-format to GitHub Actions

### ISSUE THREAD

**Issue by Sean-Der** [sepfy/libpeer#114]
@sepfy Would it be ok if I added clang-format to GitHub actions? Mixing of indentation sometimes is confusing me.

What style do you prefer?  https://gist.github.com/andrewseidl/8066c18e97c40086c183

**Comment by sepfy** [comment]
yes. it's ok to add clang format. i prefer Chromium style

**Comment by Sean-Der** [comment]
Resolved with https://github.com/sepfy/libpeer/commit/dfd7c244b6c2fc81cb5206ef2c4afba875523be3
