### ISSUE TITLE
esp32 sample won't connect to the browser 

### ISSUE THREAD

**Issue by anpin** [sepfy/libpeer#119]
Hello, I'm evaluating this library for a project. When I run the esp32 sample it wouldn't connect to the frontend. It actually connected the first time, but any further attempts failed. 

![image](https://github.com/user-attachments/assets/b9281af3-cc1e-4182-ae08-c6053a0e88d4)

My esp32 and laptop are on the same network, both are right next to a router.

Any thoughts where I should poke?

**Comment by sepfy** [comment]
hi, i guess you can try to refresh the web page? because web page will send request to device when initialize. you need wait device is connected to server, then open the browser

**Comment by anpin** [comment]
I tried to restart the browser and also different browsers and devices. Once I saw an STUN log message after the lines there, but that’s it.

I also try to change device / client id to a random MAC address value.

Could this be limitation of public ally accessible services used by the sample?

**Comment by sepfy** [comment]
looks the signaling server is not working for you. Are you able to change the MQTT broker for testing?
https://github.com/sepfy/libpeer/blob/main/src/peer_signaling.h#L25

**Comment by sepfy** [comment]
Hello, i checked your log again and i found your peer signaling task is not running (also camera task). you can try to reduce stack size.

**Comment by anpin** [comment]
hi @sepfy, thanks for your suggestion, I've tried the updated example from https://github.com/sepfy/libpeer/commit/b9ad64241793c70cceffc7eea77b87949a50ea59 and signaling now works fine.
