### ISSUE TITLE
connect with custom server

### ISSUE THREAD

**Issue by Param-21** [sepfy/libpeer#158]
Hi,

I want to connect with custom server instead of "https://sepfy.github.io/webrtc/?deviceId=1". Now i have changed SERVER_CONFIG in peer_signaling.h and mqtt connection establish. now when they shared offer data on that time i'm getting some errors. So is there any example code available of server side which is working with /example/generic.

Thanks

**Comment by sepfy** [comment]
@Param-21 Hello, what's your error? What do you mean by your server example? If you are referring to frontend code, you can refer to this repo.
https://github.com/sepfy/sepfy.github.io/blob/main/webrtc/index.html

**Comment by sepfy** [comment]
@HaARDIKSD297 not support yet

**Comment by HaARDIKSD297** [comment]
@sepfy Is there any available code that takes audio from server and plays on client's speaker, Currently I am using generic example code which is sending audio/video from client to server.

Thanks,
