### ISSUE TITLE
Trouble getting ESP32S3 Sense to send audio 

### ISSUE THREAD

**Issue by Rolstenhouse** [sepfy/libpeer#161]
Audio is not coming across on the web client, although video works flawlessly. 

I'm using the Xiao_ESP32S3 as referenced in the documentation and wonder if other's have been running into this issues (or if it's just me)

I have confirmed the mic works on the hardware side using the traditional Arduino code (referenced here) https://wiki.seeedstudio.com/xiao_esp32s3_sense_mic/

**Comment by sepfy** [comment]
Hello, are you testing with this site?
https://sepfy.github.io/webrtc/
And does your console print messages about audio bitrate?

**Comment by sepfy** [comment]
Fixed 9135cde2a444464619c9e5f9fc29b218a904c20c
