### ISSUE TITLE
fix memory leak & thread leak

### ISSUE THREAD

**Issue by topworldcoder** [sepfy/libpeer#169]
Hi, I found that libpeer may need to fix the following two issues:
1. g_ps.net_ctx is used by ssl_transport_connect, but ssl_transport_disconnect is not called to release it. (This will cause memory leaks for mqtt signaling.)
2. usrsctp_finish is needed, otherwise it will cause thread leaks.

You can refer to pull request #168.

Best regards.

**Comment by sepfy** [comment]
Merged
