### ISSUE TITLE
Documention Improvements 

### ISSUE THREAD

**Issue by cloudties** [sepfy/libpeer#22]
Documentation ( If Missing libraries and tools ) 

1) CMake >3.17 needed for meson 
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
sudo apt-get update
sudo apt install cmake
sudo apt install cmake-curses-gui  # Recommended, includes ccmake.

2) While running ./build-third-party.sh

While compiling add missing lib/headers 
sudo apt-get install -y gnutls-bin libgupnp-igd-1.0-dev libgirepository1.0-dev libgnutls.*-dev

3) In Get Started add "cd pear" step
git clone --recursive https://github.com/sepfy/pear
 cd pear
./build-third-party.sh

**Comment by sepfy** [comment]
libnice is no longer used
