### ISSUE TITLE
Build issue while running  build-third-party.sh

### ISSUE THREAD

**Issue by cloudties** [sepfy/libpeer#23]
1) Both on Ubunthu 20.04 and Pi-bullseye will get this issue
Open Issue : not able to identify 
Has header "net/in.h" : NO

**Comment by ByridianBlack** [comment]
I have the same issue. Is this project still being actively maintained? I believe I found a vulnerability but can't compile or build correctly to verify.

**Comment by sepfy** [comment]
could you provide more error log?

**Comment by sepfy** [comment]
The project structure has changed a lot. If there are still problems, please restart the problem.
