### ISSUE TITLE
I do not connect rtsp use pear rtspsrc location=rtsp

### ISSUE THREAD

**Issue by huynhphong1611** [sepfy/libpeer#30]
I do not connect rtsp use pear rtspsrc location=rtsp .
Can you help me connect rtsp with example?

**Comment by sepfy** [comment]
hi, if you want to use rtsp video stream as a source. can try to modify the pipeline of surveillance to
```
rtspsrc location=<rtsp url> ! rtph264depay ! h264parse ! rtph264pay name=rtp config-interval=-1 ssrc=1 ! appsink name=peer-connection-sink
```

**Comment by huynhphong1611** [comment]
Thank you ,
I tried and succeeded !

**Comment by huynhphong1611** [comment]
Hi, 
I have tried and succeeded with video .
But no sound from rtsp. Although my rtsp server has sound.

Can you help me add this sound? Thank you.

**Comment by huynhphong1611** [comment]
I think you should have an example of rtsp using pear.
Because IP cameras mainly use rtsp as a video source.

**Comment by sepfy** [comment]
There are currently no plans to support this feature
