### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by caoluong2k** [sepfy/libpeer#37]
Why is it that in the video on demand application in WebRTC, when a packet is dropped, the data on the web side only experiences buffering, whereas in the surveillance application, the web side receives video with broken frames?

**Comment by sepfy** [comment]
Is it the same problem every time? i am not sure how does browser process the packet. Maybe the difference is what kind of packet is dropped. if just drop a rtp packet of P frame, it still can use. but if lose the key frame, it need to buffer and wait to receive the correct key frame.
