### ISSUE TITLE
Realtime messaging data channel example

### ISSUE THREAD

**Issue by rjjrbatarao** [sepfy/libpeer#41]
I have successfully sent json data from the esp32 to the webrtc website but i dont know how we can send data from website to the esp32. is there any receive handler on the esp32 libpeer side?

**Comment by sepfy** [comment]
I pushed the code that have some event callback for ESP32. You can try it
https://github.com/sepfy/libpeer/blob/main/examples/esp32/main/app_main.c#L57

**Comment by rjjrbatarao** [comment]
woah thats fast thank you, I'll test it
