### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by richlegrand** [sepfy/libpeer#57]
I'm noticing that some devices (phones) only have ipv6 addresses available.  What is needed to support ipv6?  Here's what I see:

1) Add ipv6 support to open, bind, sendto, etc. in udp.c, and address.c.
2) Get ipv6 addresses (local and global?) from device. 
3) ipv6 STUN
4) Generate ipv6 ice candidates and an ipv6 reflexive candidate if needed.
5) Generate candidate pairs by only matching local ipv4s to remote ipv4s and local ipv6s to remote ipv6s.

I feel like I can give these a try, but there are probably other things that I haven't thought of -- let me know your thoughts :)    

thanks!

**Comment by nonibytes** [comment]
Did you make any progress on this?

**Comment by sepfy** [comment]
Added ipv6 support:
https://github.com/sepfy/libpeer/pull/72
