### ISSUE TITLE
Where to set ICE Candidate generate by remote？

### ISSUE THREAD

**Issue by dybai** [sepfy/libpeer#63]
After calling peerConnection.createAnswer() on the H5 side, the 'icecandidate' event of the peerConnection returned an ICE Candidate, like this:
`{"candidate":"candidate:1 1 TCP 2105524479 10.200.0.2 9 typ host tcptype active","sdpMid":"video","sdpMLineIndex":0,"usernameFragment":"c976a1ab"}`
However, I haven't found how to set the ICE Candidate data in libpeer?

**Comment by Sean-Der** [comment]
I am working on `add_ice_candidate` should have PR soon!
