### ISSUE TITLE
ports_resolve_mdns_host always return -1 for ESP32

### ISSUE THREAD

**Issue by Roman-Lukin** [sepfy/libpeer#66]
In the file ports.c, in the function `int ports_resolve_mdns_host(const char *host, Address *addr)`
in line #124 please add `ret = 0;`
because `ports_resolve_mdns_host` always return -1 for ESP32.

**Comment by sepfy** [comment]
update mdns code
5c53b6217a27b96eaf4a8699c7b32855de332643
