### ISSUE TITLE
More documentation please + Arduino support if possible

### ISSUE THREAD

**Issue by snimavat** [sepfy/libpeer#67]
Looks very promising library that could benefit many of the embedded / arduino projects
However, there are absolutely no docs except few samples, it makes it really hard for some one to use the library effectively.

It would be great if there can be atleast some type of documentation that explains the API exposed by this library.

- How to use it for exchanging P2P data (through TCP, if possible)
- How to use TURN if STUN is not viable 

And if possible, ways to port it to Arduino

**Comment by sepfy** [comment]
Duplicate with #65
