### ISSUE TITLE
Easy install

### ISSUE THREAD

**Issue by karaxuna** [sepfy/libpeer#75]
Can this work by simply running `idf.py add-dependency sepfy/libpeer`?

**Comment by sepfy** [comment]
Hello, I've uploaded the lib to component registry, you can test with `idf.py add-dependency sepfy/libpeer`

**Comment by karaxuna** [comment]
@sepfy that's amazing! Only problem is that it does not work with `-DHAVE_USRSCTP` flag:

```
managed_components/sepfy__libpeer/src/sctp.c:7:10: fatal error: usrsctp.h: No such file or directory
    7 | #include <usrsctp.h>
```

**Comment by sepfy** [comment]
Hello, Since the ESP32 currently doesn't support using USRSCTP, it defaults to my simplified implementation of SCTP. Thanks to @richlegrand  for helping to port USRSCTP to the ESP32. You can refer to this branch for the progress.
https://github.com/sepfy/libpeer/tree/esp32-usrsctp

**Comment by karaxuna** [comment]
That's great! Looking forward to it. I would like to contribute, but I'm
very new to this (I'm a web developer).

**Comment by karaxuna** [comment]
Hi, any progress on this? Can I help somehow? It's very critical for me.

**Comment by sepfy** [comment]
Hi~ what's feature you need in your project? If you are looking for data channel, libpeer can support it without usrsctp

**Comment by karaxuna** [comment]
I have esp32-cam and want to send images via data channel. How to do it
without usrsctp? And then what's the purpose of usrsctp?

**Comment by sepfy** [comment]
you can refer this example to send image via data channel:
https://github.com/sepfy/libpeer/tree/main/examples/esp32
In fact, the default implementation uses a simple SCTP implemented by libpeer. While this implementation might lack some features, such as packet loss detection, it can still be used to transmit images. We want to try using usrsctp on the ESP32 to see if it can replace the internal SCTP.

**Comment by karaxuna** [comment]
Awesome, it worked! Thank you! I've pushed some prs.
