### ISSUE TITLE
example: esp32s3 compile error no wifi.c

### ISSUE THREAD

**Issue by FlyLu** [sepfy/libpeer#76]
hi,  sepfy

wifi.c is removed in example esp32, But example esp32s3 adds wifi.c to CMakeLists.txt

**Comment by robbietree8** [comment]
I think you can refer to this commit https://github.com/sepfy/libpeer/commit/7af49b6338594e493792d132740a782e35406c06

**Comment by sepfy** [comment]
Removed wifi.c. Use ESP32 connect example
