### ISSUE TITLE
how to test the sample

### ISSUE THREAD

**Issue by KevinForever** [sepfy/libpeer#80]
I run the example/sample,but failed.Could you tell me how to test the sample,thanks.

root@rabbitmq-01:/home/mediaserver/libpeer/build# ./examples/sample/sample 
open https://sepfy.github.io/webrtc?deviceId=test_3096542
INFO	/home/mediaserver/libpeer/src/peer_connection.c	185	Datachannel allocates heap size: 153600
INFO	/home/mediaserver/libpeer/src/peer_connection.c	190	Audio allocates heap size: 332800
INFO	/home/mediaserver/libpeer/src/peer_connection.c	201	Video allocates heap size: 332800
INFO	/home/mediaserver/libpeer/src/ports.c	159	AF_INET
INFO	/home/mediaserver/libpeer/src/tcp.c	48	port: 8883
INFO	/home/mediaserver/libpeer/src/tcp.c	49	addr: 91.121.93.94
INFO	/home/mediaserver/libpeer/src/tcp.c	55	Connected to server
INFO	/home/mediaserver/libpeer/src/ssl_transport.c	82	start to handshake
INFO	/home/mediaserver/libpeer/src/ssl_transport.c	90	handshake success
INFO	/home/mediaserver/libpeer/src/peer_signaling.c	321	MQTT_Connect succeeded.
INFO	/home/mediaserver/libpeer/src/peer_signaling.c	271	MQTT_PACKET_TYPE_PUBLISH
state is changed: new
INFO	/home/mediaserver/libpeer/src/peer_connection.c	281	ice_servers: stun:stun.l.google.com:19302

INFO	/home/mediaserver/libpeer/src/udp.c	67	local port: 33969
INFO	/home/mediaserver/libpeer/src/agent.c	28	create IPv4 UDP socket: 4
INFO	/home/mediaserver/libpeer/src/agent.c	258	resolved_addr.port: 19302
INFO	/home/mediaserver/libpeer/src/ports.c	159	AF_INET
INFO	/home/mediaserver/libpeer/src/agent.c	265	resolved_addr.ipv4: 74.125.250.129
INFO	/home/mediaserver/libpeer/src/ice.c	83	candidate->addr.family: 2
INFO	/home/mediaserver/libpeer/src/peer_signaling.c	271	MQTT_PACKET_TYPE_PUBLISH
INFO	/home/mediaserver/libpeer/src/peer_signaling.c	271	MQTT_PACKET_TYPE_PUBLISH
state is changed: new
INFO	/home/mediaserver/libpeer/src/peer_connection.c	281	ice_servers: stun:stun.l.google.com:19302

INFO	/home/mediaserver/libpeer/src/udp.c	67	local port: 58943
INFO	/home/mediaserver/libpeer/src/agent.c	28	create IPv4 UDP socket: 5
INFO	/home/mediaserver/libpeer/src/agent.c	258	resolved_addr.port: 19302
INFO	/home/mediaserver/libpeer/src/ports.c	159	AF_INET
INFO	/home/mediaserver/libpeer/src/agent.c	265	resolved_addr.ipv4: 74.125.250.129
INFO	/home/mediaserver/libpeer/src/ice.c	83	candidate->addr.family: 2
INFO	/home/mediaserver/libpeer/src/peer_signaling.c	271	MQTT_PACKET_TYPE_PUBLISH
state is changed: checking
state is changed: failed

**Comment by sepfy** [comment]
What's your client? Is it on the same network or a different one?

**Comment by sepfy** [comment]
close this first. if still has an issue, please reopen or use discord
